# Generated by Django 3.2.7 on 2022-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('streamed_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('stream_link', models.URLField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
