# Generated by Django 3.2.7 on 2022-06-21 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_podcast_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('tag_line', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=75)),
                ('services', models.CharField(choices=[('FH', 'Fashion'), ('MU', 'Music'), ('BE', 'Beauty'), ('FM', 'FMCG'), ('TV', 'TV'), ('AM', 'Automotive'), ('SP', 'Sport'), ('TR', 'Travel'), ('FO', 'Food'), ('GA', 'Gaming'), ('SO', 'Social Cause')], default='FO', max_length=2)),
                ('about_company', models.TextField()),
                ('moderators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
