# Generated by Django 3.2.7 on 2022-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='brand_logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
