# Generated by Django 3.2.7 on 2022-06-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organisation_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='unique_identifier',
            field=models.CharField(default='uniqueurl', help_text='Please make sure the name you provide is unique, in lower cap, has no whitespace - to adhere to a good API design.', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
