# Generated by Django 3.2.7 on 2022-06-21 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_organisation_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='moderators',
        ),
        migrations.CreateModel(
            name='OrganisationModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_of', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_by', to='core.organisation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
