# Generated by Django 3.2.7 on 2022-06-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220621_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationmoderator',
            name='organisation',
        ),
        migrations.AddField(
            model_name='organisation',
            name='moderator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_of', to='core.organisationmoderator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='organization_website',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationmoderator',
            name='Consent for communication',
            field=models.BooleanField(blank=True, default=None, verbose_name='I agree to be contacted later on by team Creatar for verification.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationmoderator',
            name='position_in_company',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organisationmoderator',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
